package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import skinsenor.jcgf.com.greendaodemo.wy.dbdao.PagerBModel;
import skinsenor.jcgf.com.greendaodemo.wy.dbdao.PagerDBModel.PagerBModelConverter;

import skinsenor.jcgf.com.greendaodemo.wy.dbdao.PagerDBModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAGER_DBMODEL".
*/
public class PagerDBModelDao extends AbstractDao<PagerDBModel, Long> {

    public static final String TABLENAME = "PAGER_DBMODEL";

    /**
     * Properties of entity PagerDBModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Position = new Property(1, int.class, "position", false, "PERSITION");
        public final static Property PagerBModel = new Property(2, String.class, "pagerBModel", false, "PAGER_BMODEL");
    }

    private final PagerBModelConverter pagerBModelConverter = new PagerBModelConverter();

    public PagerDBModelDao(DaoConfig config) {
        super(config);
    }
    
    public PagerDBModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAGER_DBMODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PERSITION\" INTEGER NOT NULL ," + // 1: position
                "\"PAGER_BMODEL\" TEXT);"); // 2: pagerBModel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAGER_DBMODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PagerDBModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPosition());
 
        PagerBModel pagerBModel = entity.getPagerBModel();
        if (pagerBModel != null) {
            stmt.bindString(3, pagerBModelConverter.convertToDatabaseValue(pagerBModel));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PagerDBModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPosition());
 
        PagerBModel pagerBModel = entity.getPagerBModel();
        if (pagerBModel != null) {
            stmt.bindString(3, pagerBModelConverter.convertToDatabaseValue(pagerBModel));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PagerDBModel readEntity(Cursor cursor, int offset) {
        PagerDBModel entity = new PagerDBModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // position
            cursor.isNull(offset + 2) ? null : pagerBModelConverter.convertToEntityProperty(cursor.getString(offset + 2)) // pagerBModel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PagerDBModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPosition(cursor.getInt(offset + 1));
        entity.setPagerBModel(cursor.isNull(offset + 2) ? null : pagerBModelConverter.convertToEntityProperty(cursor.getString(offset + 2)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PagerDBModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PagerDBModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PagerDBModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
